import { Injectable } from '@angular/core';

export interface Product { 
      id :number;
      title : string;
      categoryId? : number;
      categoryTitle? : string;
      description :string; 
      img :string;
      price:number;
      ingredients?: number;
      calories?: number;
}


@Injectable({
  providedIn: 'root'
})

export class ProductListService {

    getProduct(): Product[]{
    return [
      { id : 21, 
        title:'Lime aperol spritz',
        categoryId:9,
        categoryTitle:'Cocktails',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/limeaperolspritz.jpeg",
        price: 4.50,
        ingredients: 4,
        calories: 100,
      },
      { id : 22, 
        title:'Irish coffee',
        categoryId:7,
        categoryTitle:'Hot Drinks',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/irishcoffee.jpg",
        price: 10.50,
        ingredients: 3,
        calories: 150,
      },
      { id : 23, 
        title:'Hot buttered rum',
        categoryId:7,
        categoryTitle:'Hot Drinks',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/hotbutteredrum.jpg",
        price: 15.5,
        ingredients: 5,
        calories: 200,
      },
      { id : 24, 
        title:'Subak Hwachae',
        categoryId:8,
        categoryTitle:'Fresh Drinks',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/subakhwachae.jpg",
        price: 5.50,
        ingredients: 4,
        calories: 135,
      },
      { id : 25, 
        title:'Yogurt',
        categoryId:3,
        categoryTitle:'Dairy',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/yogurt.jpg",
        price: 5.50,
        ingredients: 4,
        calories: 135,
      },
      { id : 26, 
        title:'Saltine Crackers',
        categoryId:1,
        categoryTitle:'Bakery',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/saltineCrackers.jpg",
        price: 7.50,
        ingredients: 4,
        calories: 135,
      },
      { id : 1 , 
        title:'French Bread',
        categoryId:1,
        categoryTitle:'Bakery',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/frenchbread.jpg",
        price: 4.50,
        ingredients: 10,
        calories: 245,
      },
      { id : 2 ,
        title: 'Croissants',
        categoryId:1,
        categoryTitle:'Bakery',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/croissants.jpg",
        price: 5.50, 
        ingredients: 9,
        calories: 250
      },
      { id : 3 , 
        title: 'Pizza',
        categoryId:2,
        categoryTitle:'Takeaway',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/pizza.jpg",
        price: 10.50,
        ingredients: 11,
        calories: 200
      },
      { id : 4 , 
        title: 'Milk',
        categoryId:3,
        categoryTitle:'Dairy',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/milk.jpg",
        price: 14.50,
        ingredients: 14,
        calories: 300
      },
      { id : 5 , 
        title: 'Cream Cheese',
        categoryId:3,
        categoryTitle:'Dairy',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/creamcheese.jpg",
        price: 42.50,
        ingredients: 6,
        calories: 500
      },
      { id : 6, 
        title: 'Pork Halal',
        categoryId:4,
        categoryTitle:'Meat',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/pork1.jpg",
        price: 4.00,
        ingredients: 7,
        calories: 245
      },
      { id : 7, 
        title: 'Pork Tenderloin',
        categoryId:4,
        categoryTitle:'Meat',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/pork2.jpg",
        price: 2.50,
        ingredients: 18,
        calories: 120
      },
      { id : 8, 
        title: 'Ground Beef',
        categoryId:4,
        categoryTitle:'Meat',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/groundbeef.jpg",
        price: 11.50,
        ingredients: 8,
        calories: 135
      },
      { id : 9, 
        title: 'Tuna',
        categoryId:5,
        categoryTitle:'Seafood',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/tuna.jpg",
        price: 1.11,
        ingredients: 15,
        calories: 122
      },
      { id : 10, 
        title: 'Salmon',
        categoryId:5,
        categoryTitle:'Seafood',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/salmon.jpg",
        price: 2.22,
        ingredients: 10,
        calories: 222
      },
      { id : 11, 
        title: 'Oysters',
        categoryId:5,
        categoryTitle:'Seafood',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/oysters.jpg",
        price: 4.50,
        ingredients: 13,
        calories: 111
      },
      { id : 12, 
        title: 'Scalops',
        categoryId:5,
        categoryTitle:'Seafood',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/scalops.jpg",
        price: 4.50,
        ingredients: 5,
        calories: 100
      },
      { id : 13, 
        title: 'Banana',
        categoryId:6,
        categoryTitle:'Fruit & Veg',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/banana.jpg",
        price: 4.50,
        ingredients: 4,
        calories: 90
      },
      { id : 14, 
        title:'Cucumber',
        categoryId:6,
        categoryTitle:'Fruit & Veg',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/cucumber.jpg",
        price: 4.50,
        ingredients: 6,
        calories: 40
      },
      { id : 15, 
        title:'Apple',
        categoryId:6,
        categoryTitle:'Fruit & Veg',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/apple.jpg",
        price: 4.50,
        ingredients: 9,
        calories: 220
      },
      { id : 16, 
        title:'Lemon',
        categoryId:6,
        categoryTitle:'Fruit & Veg',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/lemon.jpg",
        price: 2.50,
        ingredients: 14,
        calories: 190
      },
      { id : 17, 
        title:'Hot Chocolate',
        categoryId:7,
        categoryTitle:'Hot Drinks',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/hotchoclate.jpg",
        price: 4.50,
        ingredients: 10,
        calories: 170
      },
      { id : 18, 
        title: 'Fresh Lemon',
        categoryId:8,
        categoryTitle:'Fresh Drinks',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/lemonfresh.jpg",
        price: 4.50,
        ingredients: 12,
        calories: 112
      },
      { id : 19, 
        title: 'Fresh Orange',
        categoryId:8,
        categoryTitle:'Fresh Drinks',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/orangefresh.jpg",
        price: 4.50,
        ingredients: 6,
        calories: 30
      },
      { id : 20, 
        title:'Tequila Sunrise',
        categoryId:9,
        categoryTitle:'Cocktails',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/TequilaSunriseCocktail.jpg",
        price: 4.50,
        ingredients: 3,
        calories: 10
      },
      
      { id : 27, 
        title:'Cookie',
        categoryId:1,
        categoryTitle:'Bakery',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/cookie.jpeg",
        price: 2.50,
        ingredients: 4,
        calories: 300,
      },
      { id : 28, 
        title:'Brownie',
        categoryId:1,
        categoryTitle:'Bakery',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/brownie.jpg",
        price: 3.50,
        ingredients: 7,
        calories: 200,
      },
      { id : 29, 
        title:'Bagel',
        categoryId:1,
        categoryTitle:'Bakery',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/bagel.jpg",
        price: 4.00,
        ingredients: 7,
        calories: 185,
      },
      { id : 30, 
        title:'Whey',
        categoryId:3,
        categoryTitle:'Dairy',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/whey.png",
        price: 15.00,
        ingredients: 2,
        calories: 50,
      },
      { id : 31, 
        title:'Butter',
        categoryId:3,
        categoryTitle:'Dairy',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/butter.jpg",
        price: 10.00,
        ingredients: 2,
        calories: 150,
      },
      { id : 32, 
        title:'Meatball',
        categoryId:4,
        categoryTitle:'Meat',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/meatball.jpg",
        price: 10.00,
        ingredients: 2,
        calories: 150,
      },
      { id : 33, 
        title:'Trout',
        categoryId:5,
        categoryTitle:'Seafood',
        description:'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock,',
        img: "/assets/product/trout.jpg",
        price: 25.00,
        ingredients: 2,
        calories: 85,
      },
    ]
  } 



  getProductPrice(id:number): number {
    const product = this.getProduct().filter(product => product.id == id)[0];
    return product.price;

  }
  getProductByCategoryId(id: number): Product[] {
    return this.getProduct().filter(product => product.categoryId === id)
  }
  
  getProductById(id:number) {
    return this.getProduct().filter(product => product.id == id);
  }

  searchBox(title:string){
    if(title == ''){
      return this.getProduct()}
    else {
      return this.getProduct().filter(product => {
        return product.title.toLowerCase() == title.toLowerCase();
      });
    }
  }
  constructor() { }
}